[buildPlans.bmono]
family = "Bmono"
spacing = "fontconfig-mono"
serifs = "sans"

  [buildPlans.bmono.variants]
  inherits = "ss20"

    [buildPlans.bmono.variants.design]
    capital-g = "toothless-rounded-serifless-hooked"
    l = "serifed-tailed"
    zero = "dotted"
    three = "flattop"
    eight = "two-circles"
    asterisk = "low"
    caret = "low"
    paren = "large-contour"
    dollar = "open"
    cent = "open"
    percent = "rings-continuous-slash"

  [buildPlans.bmono.ligations]
  inherits = "dlig"

[buildPlans.bmono.widths.normal]
shape = 576
menu = 5
css = "normal"
